#!/bin/awk -f
# SPDX-License-Identifier: EUPL-1.2+
# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>

# Usage: /etc/shared-dir -v servicename=[servicename]

BEGIN {
	split(servicename, names, ":")
	print("/ext/svc/data/" names[1] "/shared-dirs/" names[2] "/dir")
}
