= Communication in Spectrum
:description: Channels, announcements and so on.
:page-nav_order: 1
:page-parent: Contributing

// SPDX-FileCopyrightText: 2023 Unikie
// SPDX-License-Identifier: GFDL-1.3-no-invariants-or-later OR CC-BY-SA-4.0

There are several places online in which announcements,
discussion, and collaboration happen. Rather than tell
you about them all at once, though, it is best to tell you
which ones are relevant to you, given how you would like
to participate (or not) in the project.

Our primary methods of communication are mailing lists and IRC.
If this is not how you are used to interacting with free
software projects, *DON'T PANIC*.

We provide instructions for how to get started, and several
different interfaces for you to choose from depending on what workflow
(web, mail, Atom, etc.) makes you most comfortable. Details of these
will be explained further on, but first, you should figure out what
communication channels are actually relevant for you.

If you are interested in keeping up to date with announcements from
Spectrum's developers, subscribe to *announce@spectrum-os.org*.
You can discuss Spectrum and related topics in real time on IRC, or
more long-form on spectrum-announce (_discuss@spectrum-os.org_).
Finally, development work happens in Spectrum's
https://spectrum-os.org/git/[source repositories], and is discussed on
spectrum-devel (_devel@spectrum-os.org_).


== Internet Relay Chat

There is a single Internet Relay Chat (IRC) channel,
link:ircs://irc.libera.chat:6697/spectrum[#spectrum] on
https://libera.chat/[Libera.Chat], for all kinds of Spectrum
discussions.  You can also join through https://matrix.org/[Matrix] as
https://matrix.to/#/#spectrum:libera.chat[#spectrum:libera.chat].
If you are new to IRC, you might find Matrix the easiest way to get started.
The channel is *logged*, but the logs are not available online yet.


== Mailing Lists

If you are interested in participating in the project, or even just
following along with it, the best thing to do is subscribe to one or
more of the Spectrum mailing lists.

If mailing lists are not your thing, that is okay! Try the
https://spectrum-os.org/lists/hyperkitty/[Web UI], which allows you to
interact with the mailing lists much like a modern web forum.

Each list has https://spectrum-os.org/lists/archives/[archives] that
can also be accessed via the web, NNTP or Atom. You are strongly
encouraged to mirror them.

[cols="1,1"]
|===

|announce@spectrum-os.org
|This is a one-way list where announcements
from Spectrum's developers will be posted.

You can subscribe
https://spectrum-os.org/lists/mailman3/lists/announce.spectrum-os.org/[on the web],
or by sending mail to *announce-subscribe@spectrum-os.org*.

|discuss@spectrum-os.org
|This list contains high-level discussion about the project.

You can subscribe
https://spectrum-os.org/lists/mailman3/lists/discuss.spectrum-os.org/[on the web],
or by sending mail to *discuss-subscribe@spectrum-os.org*.

|devel@spectrum-os.org
|This list is where low-level technical discussions happen,
and where patches are sent.

There is a separate guide for the Spectrum development process,
including how patches are sent to this list and discussed.
For more information, see
xref:working-with-patches.adoc[Working with Patches].

You can subscribe
https://spectrum-os.org/lists/mailman3/lists/devel.spectrum-os.org/[on the web], or by sending mail to *devel-subscribe@spectrum-os.org*.

|===
