# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>

# Generated by scripts/update-nixpkgs.sh.

import (builtins.fetchTarball {
  url = "https://spectrum-os.org/git/nixpkgs/snapshot/nixpkgs-7b3e60ade3c3bb3699125b81e65b76c54e700255.tar.gz";
  sha256 = "1mis4mb4xq9vpcg2kdayrpmm5ja603zrbv14b4ifwj1ay5sliw2y";
})
