#! /usr/bin/env nix-shell
#! nix-shell -i bash -p curl jq

# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>
# SPDX-License-Identifier: EUPL-1.2+
# REUSE-IgnoreStart

# shellcheck shell=bash

set -ueo pipefail

root="$(dirname "$0")/.."
out="$(mktemp -p "$root/lib" -t nixpkgs.default.nix.XXXXXXXXXX)"

exec > "$out"

rev="$(
	curl -fsLS https://api.github.com/repos/NixOS/nixpkgs/branches/${1-nixos-unstable} |
	jq -r .commit.sha
)"
url="https://github.com/NixOS/nixpkgs/archive/$rev.tar.gz"

cat <<EOF
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>

# Generated by scripts/update-nixpkgs.sh.

import (builtins.fetchTarball {
  url = "$url";
  sha256 = "$(nix-prefetch-url --unpack "$url")";
})
EOF

mv -- "$out" "$root/lib/nixpkgs.default.nix"
