#! /usr/bin/env nix-shell
#! nix-shell -i bash -p curl

# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>
# SPDX-License-Identifier: EUPL-1.2+
# REUSE-IgnoreStart

# shellcheck shell=bash

set -ueo pipefail

root="$(dirname "$0")/.."
out="$(mktemp -p "$root/lib" -t nixpkgs.default.nix.XXXXXXXXXX)"

exec > "$out"

rev="$(
	curl -fsLS https://spectrum-os.org/git/nixpkgs.git/info/refs |
	awk '$2 == "refs/heads/rootfs" { print $1 }'
)"
url="https://spectrum-os.org/git/nixpkgs/snapshot/nixpkgs-$rev.tar.gz"

cat <<EOF
# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>

# Generated by scripts/update-nixpkgs.sh.

import (builtins.fetchTarball {
  url = "$url";
  sha256 = "$(nix-prefetch-url --unpack "$url")";
})
EOF

mv -- "$out" "$root/lib/nixpkgs.default.nix"
